export const GET_DISCOUNTS_REQUEST = 'GET_DISCOUNTS_REQUEST'
export const GET_DISCOUNTS_SUCCESS = 'GET_DISCOUNTS_SUCCESS'
export const GET_DISCOUNTS_FAIL = 'GET_DISCOUNTS_FAIL'

export const CREATE_DISCOUNT_REQUEST = 'CREATE_DISCOUNT_REQUEST'
export const CREATE_DISCOUNT_SUCCESS = 'CREATE_DISCOUNT_SUCCESS'
export const CREATE_DISCOUNT_FAIL = 'CREATE_DISCOUNT_FAIL'

export const DELETE_DISCOUNT = 'DELETE_DISCOUNT'