export const GET_FRAGRANCES_REQUEST = 'GET_FRAGRANCES_REQUEST'
export const GET_FRAGRANCES_SUCCESS = 'GET_FRAGRANCES_SUCCESS'
export const GET_FRAGRANCES_FAIL = 'GET_FRAGRANCES_FAIL'

export const GET_FRAGRANCE_REQUEST = 'GET_FRAGRANCE_REQUEST'
export const GET_FRAGRANCE_SUCCESS = 'GET_FRAGRANCE_SUCCESS'
export const GET_FRAGRANCE_FAIL = 'GET_FRAGRANCE_FAIL'

export const CREATE_FRAGRANCE_REQUEST = 'CREATE_FRAGRANCE_REQUEST'
export const CREATE_FRAGRANCE_SUCCESS = 'CREATE_FRAGRANCE_SUCCESS'
export const CREATE_FRAGRANCE_FAIL = 'CREATE_FRAGRANCE_FAIL'

export const DELETE_FRAGRANCE = 'DELETE_FRAGRANCE'