export const GET_SHIPPINGS_REQUEST = 'GET_SHIPPINGS_REQUEST'
export const GET_SHIPPINGS_SUCCESS = 'GET_SHIPPINGS_SUCCESS'
export const GET_SHIPPINGS_FAIL = 'GET_SHIPPINGS_FAIL'

export const CREATE_SHIPPING_REQUEST = 'CREATE_SHIPPING_REQUEST'
export const CREATE_SHIPPING_SUCCESS = 'CREATE_SHIPPING_SUCCESS'
export const CREATE_SHIPPING_FAIL = 'CREATE_SHIPPING_FAIL'

export const DELETE_SHIPPING = 'DELETE_SHIPPING'