export const GET_STORES_REQUEST = 'GET_STORES_REQUEST'
export const GET_STORES_SUCCESS = 'GET_STORES_SUCCESS'
export const GET_STORES_FAIL = 'GET_STORES_FAIL'

export const GET_STORE_REQUEST = 'GET_STORE_REQUEST'
export const GET_STORE_SUCCESS = 'GET_STORE_SUCCESS'
export const GET_STORE_FAIL = 'GET_STORE_FAIL'

export const CREATE_STORE_REQUEST = 'CREATE_STORE_REQUEST'
export const CREATE_STORE_SUCCESS = 'CREATE_STORE_SUCCESS'
export const CREATE_STORE_FAIL = 'CREATE_STORE_FAIL'

export const UPDATE_STORE_REQUEST = 'UPDATE_STORE_REQUEST'
export const UPDATE_STORE_SUCCESS = 'UPDATE_STORE_SUCCESS'
export const UPDATE_STORE_FAIL = 'UPDATE_STORE_FAIL'


export const DELETE_STORE = 'DELETE_STORE'

export const DELETE_ALL_STORES = 'DELETE_ALL_STORES'